-- Legacy migration: V8 now drops generated_changelog, so this identity fix is only needed
-- for environments where V8's drop was skipped or the table was recreated by Hibernate.
-- Guard with a table-existence check so the script is a no-op when the table is already gone.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'generated_changelog') THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            WHERE c.relname = 'generated_changelog' AND a.attname = 'id' AND a.attidentity <> ''
        ) THEN
            EXECUTE 'ALTER TABLE generated_changelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
        END IF;

        PERFORM setval(
            pg_get_serial_sequence('generated_changelog', 'id'),
            GREATEST(COALESCE((SELECT MAX(id) FROM generated_changelog), 0) + 1, 1),
            false
        );
    END IF;
END $$;
