-- Recreate old tables dropped by earlier V7/V8 migrations. The application code still
-- references generated_changelog and raw_release through the GeneratedChangelog and
-- RawRelease JPA entities (dual-write pattern). These are created empty — any previous
-- data was already backfilled into changelog_version / changelog_revision by V8 (or was
-- already gone when V8's IF EXISTS check skipped the backfill). GUARDED with IF NOT EXISTS
-- so the script is safe to run on databases where the tables somehow still exist.

CREATE TABLE IF NOT EXISTS generated_changelog (
    id BIGSERIAL PRIMARY KEY,
    project VARCHAR(255) NOT NULL,
    repo VARCHAR(255) NOT NULL,
    version VARCHAR(100),
    audience VARCHAR(50),
    current_text TEXT,
    current_source VARCHAR(10),
    current_model_id VARCHAR(255),
    current_input_hash VARCHAR(64),
    current_edited_by VARCHAR(255),
    current_at TIMESTAMP WITH TIME ZONE,
    previous_text TEXT,
    previous_source VARCHAR(10),
    previous_model_id VARCHAR(255),
    previous_input_hash VARCHAR(64),
    previous_edited_by VARCHAR(255),
    previous_at TIMESTAMP WITH TIME ZONE,
    pushed_text TEXT,
    pushed_at TIMESTAMP WITH TIME ZONE,
    pushed_pull_request_url TEXT,
    CONSTRAINT uq_generated_changelog UNIQUE (project, repo, version, audience)
);

CREATE TABLE IF NOT EXISTS raw_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project TEXT NOT NULL,
    repo TEXT NOT NULL,
    branch TEXT,
    version TEXT NOT NULL,
    stage TEXT NOT NULL,
    items TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_raw_release UNIQUE (project, repo, version)
);