-- Recorded pipeline/workflow runs — one row per provider run ID.
-- Allows the dashboard to load stored run data instead of re-fetching from the provider.
CREATE TABLE IF NOT EXISTS recorded_pipeline_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,                          -- 'azure' | 'github'
    project TEXT NOT NULL,
    repo TEXT NOT NULL,
    build_id BIGINT NOT NULL,                        -- Azure Build ID or GitHub Workflow Run ID
    version TEXT,                                    -- version reported by pipeline (optional)
    stage TEXT,                                      -- 'prerelease' | 'release' (optional)
    branch TEXT,
    run_metadata TEXT NOT NULL,                      -- complete RunChangeContext snapshot (JSON)
    change_items TEXT NOT NULL,                      -- normalized ChangeItem[] for generation (JSON)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_recorded_pipeline_run UNIQUE (provider, project, repo, build_id)
);

CREATE INDEX IF NOT EXISTS idx_recorded_pipeline_run_lookup
    ON recorded_pipeline_run (provider, project, repo, build_id);

CREATE INDEX IF NOT EXISTS idx_recorded_pipeline_run_version
    ON recorded_pipeline_run (provider, project, repo, version);