-- Per-user GitHub sign-in (OAuth App). A `github_user` row is the ONLY place user
-- credentials live: the GitHub id + login that identify the user and the OAuth
-- access token (encrypted at rest with the service's session secret). No password
-- and no email are ever stored — GitHub handles those on github.com.
--
-- `auth_session` maps an opaque, HttpOnly session cookie to one user. Deleting a
-- user cascades to its sessions (ON DELETE CASCADE), and "delete account" removes
-- ONLY these rows — generated changelogs/history live in the other tables and are
-- intentionally untouched, since they hold no user credential data.
CREATE TABLE IF NOT EXISTS github_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT NOT NULL,
    login VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(512),
    access_token BYTEA NOT NULL,
    refresh_token BYTEA,
    token_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_github_user_github_id UNIQUE (github_id),
    CONSTRAINT uq_github_user_login UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token_hash CHAR(64) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES github_user(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_auth_session_token UNIQUE (session_token_hash)
);

CREATE INDEX IF NOT EXISTS idx_auth_session_user
    ON auth_session (user_id);