-- Raw facts a pipeline reports about a release, before any AI text is written for it.
-- One row per project/repo/version; re-ingesting the same version (a pipeline retry)
-- overwrites in place rather than duplicating.
CREATE TABLE raw_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project TEXT NOT NULL,
    repo TEXT NOT NULL,
    branch TEXT,
    version TEXT NOT NULL,
    stage TEXT NOT NULL,
    items TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_raw_release UNIQUE (project, repo, version)
);

-- One row per PR, upserted as the pipeline reports it — lets a PR move from
-- prerelease to release over time without creating a second row. This is what makes
-- "which version did PR !N ship in" an indexed lookup instead of a text search.
CREATE TABLE release_pr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project TEXT NOT NULL,
    repo TEXT NOT NULL,
    pr_id INTEGER NOT NULL,
    version TEXT NOT NULL,
    stage TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_release_pr UNIQUE (project, repo, pr_id)
);
