-- Fix sequence ID conflicts between Hibernate's sequence-style generator and BIGSERIAL/IDENTITY columns.
-- All entities now use GenerationType.IDENTITY (matching BIGSERIAL/GENERATED BY DEFAULT AS IDENTITY),
-- so the explicit sequences are no longer needed for Hibernate and are dropped.
-- If any sequence was ahead of the table's max id, resetting avoids future conflicts.

DROP SEQUENCE IF EXISTS generated_changelog_SEQ;
DROP SEQUENCE IF EXISTS raw_release_SEQ;
DROP SEQUENCE IF EXISTS release_pr_SEQ;
DROP SEQUENCE IF EXISTS changelog_version_SEQ;
DROP SEQUENCE IF EXISTS changelog_revision_SEQ;