quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.ssl-mode=require
quarkus.rest.path=/api
quarkus.log.file.enable=true
quarkus.log.file.path=service.log

quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none

# Increase worker thread pool size to prevent exhaustion
quarkus.vertx.worker-pool-size=100
quarkus.vertx.max-worker-execute-time=120s